# 開発用のDockfile
# ソースに修正した内容がリアルタイムで反映される
# PWAアプリなのでキャッシュされているので、更新したら必ずキャッシュをクリアにすること

FROM node:lts-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# RUN npm run build

EXPOSE 8080
CMD ["npm","run","start"]
