sudo: required
services:
  - docker

before_install:
  - docker build -t someonesgarden/spotifire-client -f Dockerfile.dev .

script:
  - docker run  someonesgarden/spotifire-client npm run test -- --coverage
