apiVersion: certmanager.k8s.io/v1alpha1
  kind: Certificate
  metadata:
    name: spotifire-tokyo-tls
  spec:
    secretName: spotifire-tokyo
    issuerRef:
      name: letsencrypt-staging
      kind: Issuer
    commonName: spotifire.tokyo
    dnsNames:
      - spotifire.tokyo
      - www.spotifire.tokyo
    acme:
      config:
        - http01:
            ingressClass: nginx
          domains:
            - spotifire.tokyo
            - www.spotifire.tokyo
