apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: someonesgarden/spotifire-client
          ports:
            - containerPort: 3000
          env:
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mapbox-token
                  key: MAPBOX-TOKEN

