#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: ingress-service
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    # nginx.ingress.kubernetes.io/rewrite-target: /$1
#    # nginx.ingress.kubernetes.io/rewrite-target: /$2
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /
#            # - path: /?(.*)
#            # - path: /(/|$)(.*)
#            backend:
#              serviceName: client-cluster-ip-service
#              servicePort: 3000
#          - path: /api/
#            # - path: /api/?(.*)
#            # - path: /api(/|$)(.*)
#            backend:
#              serviceName: api-cluster-ip-service
#              servicePort: 5000


# FROM
# https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/rewrite

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
      - http:
          paths:
            - backend:
                serviceName: client-cluster-ip-service
                servicePort: 3000
              path: /
            - backend:
                serviceName: api-cluster-ip-service
                servicePort: 5000
              path: /something(/|$)(.*)
#        host: spotifire.tokyo
