apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - spotifire.tokyo
        - www.spotifire.tokyo
      secretName: cert-manager-tls
  rules:
    - host: spotifire.tokyo
      http:
        paths:
          - path: /
            # - path: /?(.*)
            # - path: /(/|$)(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/
            # - path: /api/?(.*)
            # - path: /api(/|$)(.*)
            backend:
              serviceName: api-cluster-ip-service
              servicePort: 5000

    - host: www.spotifire.tokyo
      http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/

            backend:
              serviceName: api-cluster-ip-service
              servicePort: 5000
